### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by gooops** [lastbackend/lastbackend#333]
```
{"level":"error","msg":"Task [9ff54b16-7d9e-4e84-a844-894e4bef057d]: container create error Error: No such image: library/nginx:latest","time":"2017-08-15 18:10:12"}
{"level":"error","msg":"Task [2b32d226-d29b-45f3-aa7f-806784f4aa9b]: container create error Error: No such image: library/nginx:latest","time":"2017-08-15 18:10:12"}
{"level":"error","msg":"Task [90d8a2fd-b773-4766-b6f5-a8a35adf051b]: container create error Error: No such image: library/nginx:latest","time":"2017-08-15 18:10:12"}
{"level":"error","msg":"Task [33634bea-e048-4606-9bad-e2e659c6fcc2]: container create error Error: No such image: library/nginx:latest","time":"2017-08-15 18:10:12"}
{"level":"error","msg":"Task [6fe49967-864c-45dd-bf52-1c3e005dd389]: container create error Error: No such image: library/nginx:latest","time":"2017-08-15 18:10:12"}
fatal error: concurrent map read and map write

goroutine 90 [running]:
runtime.throw(0xbaf327, 0x21)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc42088e840 sp=0xc42088e820
runtime.mapaccess2_faststr(0xac2c00, 0xc420434f60, 0xc420952900, 0x1c, 0x1, 0x1)
        /usr/local/go/src/runtime/hashmap_fast.go:326 +0x50a fp=0xc42088e8a0 sp=0xc42088e840
```

**Comment by lanwen** [comment]
@gooops What steps produced such error?

**Comment by undassa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [1](https://trello.com/c/CrtattAR/612-1)

**Comment by undassa** [comment]
fixed in alpha version
